### ISSUE TITLE
Facebook links not stripped of tracking info (noticed Oct 3, 2017)

### ISSUE THREAD

**Issue by one70** [canisbos/DirectLinks#4]
Self-explanatory title. Thanks for looking into this!

**Comment by canisbos** [comment]
Thanks for the report. Yes, looks like Facebook changed the way they're handling external links. Instead of using an `onclick` attribute, they now use a `data-lynx-uri` attribute, presumably in conjunction with a click handler that is attached using `addEventListener()` or equivalent. 

I can easily modify DirectLinks to strip this `data-lynx-uri` attribute. But what I don't know is whether that actually prevents Facebook from tracking the link click. Their click handler may have access to the data in that attribute through other means.

**Comment by canisbos** [comment]
I have updated DirectLinks with the aforementioned modification. Again, I do not know whether it will make any difference.

**Comment by one70** [comment]
Thanks for the explanation and update. Unfortunately I don't know how Facebook tracks clicks, my programming knowledge is poor.

**Comment by canisbos** [comment]
Yes, I think it would. But I wouldn't be surprised if it also made the site unusable.
